package gripdata

//NodeAccountKey is a key added by an account holder on
//a node.  Then another node can create an
//associate_node_account_key to match that will associate
//the node with the account.
//WARNING!  These should be generated by the node.
type NodeAccountKey struct {
	AccountID  string //Userid
	Key        string //The magic key
	Expiration uint64 //The time this key expires
	OneTime    bool
	Used       bool
}
